# Generated by Django 6.0.2 on 2026-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('title', models.TextField(help_text='Use newlines to separate lines of text')),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('cta_primary_text', models.CharField(blank=True, max_length=100)),
                ('cta_primary_target', models.CharField(default='#products', max_length=255)),
                ('cta_secondary_text', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_target', models.CharField(default='#contact', max_length=255)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
