# Generated by Django 6.0.2 on 2026-02-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='subhero/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='subhero/')),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_target', models.CharField(default='#contact', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubHeroParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('subhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='eyta.subherosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubHeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('suffix', models.CharField(blank=True, help_text='e.g. +, %, k', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='eyta.subherosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
