# Generated by Django 6.0.2 on 2026-02-26 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyta', '0002_subherosection_subheroparagraph_subherostat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='videosection/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_target', models.CharField(default='#contact', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSectionParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='eyta.videosectionmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
