# Generated by Django 6.0.2 on 2026-02-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyta', '0004_productcategory_productssectionmodel_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Internal name for the section', max_length=255)),
            ],
            options={
                'verbose_name': 'Features Section',
                'verbose_name_plural': 'Features Section',
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Truck', 'Truck'), ('ShieldCheck', 'Shield Check'), ('Leaf', 'Leaf'), ('Heart', 'Heart')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='eyta.featuressectionmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
