# Generated by Django 6.0.2 on 2026-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyta', '0005_featuressectionmodel_featureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(help_text='e.g. May 24, 2024', max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('excerpt', models.TextField()),
                ('content', models.TextField(help_text='The full article text for the modal popup')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('read_more_text', models.CharField(default='Read More', max_length=100)),
                ('view_all_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Section',
            },
        ),
    ]
