# Generated by Django 6.0.2 on 2026-02-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyta', '0006_blogpost_blogsectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about/')),
                ('background_color', models.CharField(default='#ffffff', help_text='e.g. #ffffff or #8b6d4b', max_length=50)),
                ('text_color', models.CharField(default='#000000', help_text='e.g. #000000 or #ffffff', max_length=50)),
                ('quote', models.TextField(blank=True, help_text='If provided, this pane will render as a quote block.')),
                ('attribution', models.CharField(blank=True, max_length=255)),
                ('paragraphs', models.JSONField(blank=True, default=list, help_text='Enter a JSON list of strings, e.g., ["Para 1", "Para 2"]')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Section Pane',
                'verbose_name_plural': 'About Section Panes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('cta_text', models.CharField(blank=True, help_text='Text for the contact link', max_length=100)),
                ('cta_target', models.CharField(default='#contact', max_length=255)),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='eyta.faqsectionmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
