# Generated by Django 6.0.2 on 2026-02-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyta', '0007_aboutpane_faqsectionmodel_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('location_label', models.CharField(default='Visit Us', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('email_label', models.CharField(default='Email Us', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_label', models.CharField(default='Call Us', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('name_placeholder', models.CharField(default='Your Name', max_length=100)),
                ('email_placeholder', models.CharField(default='Your Email', max_length=100)),
                ('message_placeholder', models.CharField(default='Your Message', max_length=100)),
                ('submit_text', models.CharField(default='Send Message', max_length=100)),
                ('submitting_text', models.CharField(default='Sending...', max_length=100)),
                ('submitted_text', models.CharField(default='Sent Successfully', max_length=100)),
                ('success_message', models.CharField(default='Thank you! We will get back to you soon.', max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='FooterConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_description', models.TextField()),
                ('copyright_text', models.CharField(max_length=255)),
                ('newsletter_heading', models.CharField(blank=True, max_length=255)),
                ('newsletter_description', models.TextField(blank=True)),
                ('newsletter_placeholder', models.CharField(default='Enter your email', max_length=100)),
                ('newsletter_button_text', models.CharField(default='Subscribe', max_length=100)),
                ('newsletter_success_text', models.CharField(default='Subscribed!', max_length=100)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.JSONField(default=list, help_text='Format: [{"label": "Link Name", "href": "#target"}]')),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_groups', to='eyta.footerconfigmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_links', to='eyta.footerconfigmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=50)),
                ('label', models.CharField(help_text='e.g. Follow us on Instagram', max_length=100)),
                ('href', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='eyta.footerconfigmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
