# Generated by Django 6.0.2 on 2026-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyta', '0008_contactsectionmodel_footerconfigmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosectionmodel',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload the video to be played', null=True, upload_to='videosection_videos/'),
        ),
    ]
